### ISSUE TITLE
 Project.getConvention() method has been deprecated

### ISSUE THREAD

**Issue by markwoon** [gradle-nexus/publish-plugin#281] opened 2023-10-24 21:22 UTC
After updating to gradle > 8.2 I'm getting:
```
The Project.getConvention() method has been deprecated. This is scheduled to be removed in Gradle 9.0.
Consult the upgrading guide for further information:
https://docs.gradle.org/8.4/userguide/upgrading_version_8.html#deprecated_access_to_conventions
```

Any chance of an update for this?

**Comment by TWiStErRob** [comment] 2023-10-24 21:35
Duplicate of #226, try the RC.

**Comment by remal** [comment] 2024-01-09 00:06
@TWiStErRob are there any plans regarding stable v2 releave?

**Comment by szpak** [comment] 2024-01-09 21:45
I believe that having ~3 things to sort out (#254/#171 - it's blocked on me :-/ and #274/#258) we could do it. @TWiStErRob Do you see anything else important for 2.0.0-final?

**Comment by szpak** [comment] 2024-02-01 22:19
I've just released [2.0.0-rc-2](https://github.com/gradle-nexus/publish-plugin/releases/tag/v2.0.0-rc-2). Do you see anything else to be included in 2.0.0-final?

**Comment by TWiStErRob** [comment] 2024-06-17 10:16
Closing as duplicate of https://github.com/gradle-nexus/publish-plugin/issues/226

**Closed by TWiStErRob** 2024-06-17 10:16 UTC
