### ISSUE TITLE
Could not find method nexusPublishing() for arguments on project ':library' of type org.gradle.api.Project.

### ISSUE THREAD

**Issue by jahirfiquitiva** [gradle-nexus/publish-plugin#74] opened 2021-03-03 00:23 UTC
Hello

I am getting this error ... how can I fix it? 🙏🏼

```gradle
Caused by: org.gradle.internal.metaobject.AbstractDynamicObject$CustomMessageMissingMethodException: Could not find method nexusPublishing() for arguments [publish_mavencentral_b59r6yy6puwpa4f9u3qxqhqlx$_run_closure5@4a07f25b] on project ':library' of type org.gradle.api.Project.
```

**Comment by szpak** [comment] 2021-03-03 00:27
Having your configuration (or at least its relevant fragments) would make it easier to spot the answer :-)

**Comment by jahirfiquitiva** [comment] 2021-03-03 00:30
could it be that it was missing this? `apply plugin: 'io.github.gradle-nexus.publish-plugin'`

**Comment by szpak** [comment] 2021-03-03 00:57
Definitely that could be one of the reasons.

**Comment by jahirfiquitiva** [comment] 2021-03-03 00:59
it worked after adding it 😅  ... would be nice to add that to the readme, as it isn't mentioned there

**Comment by szpak** [comment] 2021-03-03 01:08
It is: https://github.com/gradle-nexus/publish-plugin#applying-the-plugin

Applying the plugin always occurs and then you can publish to Maven Central (Sonatype Nexus) or to any other Nexus instances (the next two paragraphs).

**Comment by jahirfiquitiva** [comment] 2021-03-03 01:09
I think it's because I'm using an "old format" like this:
```gradle
apply plugin: 'io.github.gradle-nexus.publish-plugin'
buildscript {
  repositories {
    classpath "io.github.gradle-nexus:publish-plugin:1.0.0"
  }
}
```

**Comment by szpak** [comment] 2021-03-03 01:16
Yes, in that case you need to apply the plugin manually.

I wonder, if there is a corner case in the "new" plugin applying scheme in Gradle that you keep using the old one?

**Comment by jahirfiquitiva** [comment] 2021-03-03 01:25
I just don't understand it and struggle while trying to migrate, plus I haven't found the need to do so, so 🤷🏼‍♂️😬😅

**Comment by jahirfiquitiva** [comment] 2021-03-03 01:29
also... would you happen to know why this happens in a GitHub Action?
`Task :closeAndReleaseStagingRepository SKIPPED`

You can check the [action code here](https://github.com/jahirfiquitiva/Frames/blob/master/.github/workflows/publish.yml), and the [gradle configuration here](https://github.com/jahirfiquitiva/Frames/blob/master/scripts/publish-mavencentral.gradle).

Thanks

**Comment by szpak** [comment] 2021-03-03 01:31
A blind shot - you have a SNAPSHOT version in that build?

**Comment by szpak** [comment] 2021-03-03 01:36
No, `:closeAndReleaseStagingRepository` is SKIPPED if you don't have any staging repositories configured, but you seem to have one. Could you call `closeAndReleaseSonatypeStagingRepository` instead?

**Comment by jahirfiquitiva** [comment] 2021-03-03 01:36
also, when trying to run `closeAndReleaseSonatypeStagingRepository`, this happens:

```gradle
Execution failed for task ':closeSonatypeStagingRepository'.
> No staging repository with name sonatype created
```

**Comment by jahirfiquitiva** [comment] 2021-03-03 01:37
Not sure if this helps, but this is what I see on sonatype site

<img width="1901" alt="Shot 2021-03-02 at 20-37-02@2x" src="https://user-images.githubusercontent.com/10360816/109739102-0f2fc880-7b97-11eb-88e0-c73876972687.png">

**Comment by jahirfiquitiva** [comment] 2021-03-03 01:40
oh, and I'm not sure what you mean with `SNAPSHOT version` 😬🤦🏼‍♂️

**Comment by szpak** [comment] 2021-03-03 01:41
That confirms that `initializeSonatypeStagingRepository` task wasn't used (the logs say the same). Could you call `publishToSonatype closeAndReleaseStagingRepository --info` instead?

**Comment by szpak** [comment] 2021-03-03 01:42
> oh, and I'm not sure what you mean with SNAPSHOT version grimacing🤦🏼‍♂️

With version `0.8.0-SNAPSHOT` staging repositories are created nor closed.

**Comment by jahirfiquitiva** [comment] 2021-03-03 01:42
oh, I'm using v `1.0.0` of this plugin

**Comment by szpak** [comment] 2021-03-03 01:43
> oh, I'm using v 1.0.0 of this plugin

The version of your project :-). You can call `./gradlew version` before publishing to get it.

**Comment by jahirfiquitiva** [comment] 2021-03-03 01:57
I am getting this:

```gradle
* What went wrong:
Task 'publishToSonatype' is ambiguous in root project 'Frames'. Candidates are: 'publishAllPublicationsToSonatypeRepository', 'publishReleasePublicationToSonatypeRepository'.
```

**Comment by szpak** [comment] 2021-03-03 02:00
Both are good, but the second is exactly for the publication that you configured.

**Comment by jahirfiquitiva** [comment] 2021-03-03 02:01
This is the output running with `--info`

```gradle
> Task :library:publishReleasePublicationToSonatypeRepository
Task :library:publishReleasePublicationToSonatypeRepository in app Starting
Caching disabled for task ':library:publishReleasePublicationToSonatypeRepository' because:
  Build cache is disabled
Task ':library:publishReleasePublicationToSonatypeRepository' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Publishing to repository 'sonatype' (https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/)
Uploading Frames-337.aar to /service/local/staging/deploy/maven2/dev/jahir/Frames/337/Frames-337.aar
Uploading Frames-337.pom to /service/local/staging/deploy/maven2/dev/jahir/Frames/337/Frames-337.pom
Uploading Frames-337-sources.jar.asc to /service/local/staging/deploy/maven2/dev/jahir/Frames/337/Frames-337-sources.jar.asc
Uploading Frames-337.aar.asc to /service/local/staging/deploy/maven2/dev/jahir/Frames/337/Frames-337.aar.asc
Uploading Frames-337-sources.jar to /service/local/staging/deploy/maven2/dev/jahir/Frames/337/Frames-337-sources.jar
Uploading Frames-337.pom.asc to /service/local/staging/deploy/maven2/dev/jahir/Frames/337/Frames-337.pom.asc
Resource missing. [HTTP GET: https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/dev/jahir/Frames/maven-metadata.xml]
Uploading maven-metadata.xml to /service/local/staging/deploy/maven2/dev/jahir/Frames/maven-metadata.xml
Task :library:publishReleasePublicationToSonatypeRepository in app Finished
:library:publishReleasePublicationToSonatypeRepository (Thread[Daemon worker,5,main]) completed. Took 7.654 secs.
:closeAndReleaseStagingRepository (Thread[Daemon worker,5,main]) started.

> Task :closeAndReleaseStagingRepository SKIPPED
Task :closeAndReleaseStagingRepository in app Starting
Skipping task ':closeAndReleaseStagingRepository' as task onlyIf is false.
Task :closeAndReleaseStagingRepository in app Finished
:closeAndReleaseStagingRepository (Thread[Daemon worker,5,main]) completed. Took 0.0 secs.
```

This is the output running with `--info`

**Comment by szpak** [comment] 2021-03-03 02:04
Can you remove that extra repository configuration section?
https://github.com/jahirfiquitiva/Frames/blob/master/scripts/publish-mavencentral.gradle#L98

**Comment by jahirfiquitiva** [comment] 2021-03-03 02:08
removing that caused this to happen:
```gradle
> Configure project :library
Evaluating project ':library' using build file '/Users/jahir/dev/jahir/android/frames/library/build.gradle'.
Creating configuration androidTestUtil
Warning: The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.
WARNING: API 'variant.getJavaCompile()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.
It will be removed in version 5.0 of the Android Gradle plugin.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getJavaCompile(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
Configuring Java sources compilation with source level 1.8 and target level 1.8.
Configuring Java sources compilation with source level 1.8 and target level 1.8.
All projects evaluated.
Analytics other plugin to proto: Unknown plugin type io.github.gradlenexus.publishplugin.NexusPublishPlugin expected enum IO_GITHUB_GRADLENEXUS_PUBLISHPLUGIN_NEXUSPUBLISHPLUGIN
Analytics other plugin to proto: Unknown plugin type org.jetbrains.kotlin.gradle.internal.AndroidSubplugin expected enum ORG_JETBRAINS_KOTLIN_GRADLE_INTERNAL_ANDROIDSUBPLUGIN
Analytics other plugin to proto: Unknown plugin type org.jetbrains.kotlin.gradle.internal.AndroidSubplugin expected enum ORG_JETBRAINS_KOTLIN_GRADLE_INTERNAL_ANDROIDSUBPLUGIN
Analytics other plugin to proto: Unknown plugin type org.gradle.api.publish.plugins.PublishingPlugin expected enum ORG_GRADLE_API_PUBLISH_PLUGINS_PUBLISHINGPLUGIN

FAILURE: Build failed with an exception.

* What went wrong:
Task 'publishReleasePublicationToSonatypeRepository' not found in root project 'Frames'.
```

**Comment by szpak** [comment] 2021-03-03 02:19
This suggests that GNPP (this plugin) doesn't correctly detect publishing configuration in an Android project. As a result, it doesn't enhance the publishing task to use the explicitly created staging repository and in general - doesn't work.

I don't have an Android SDK installed locally and I would prefer not to setup it. However, if you created/generated (or stripped down the current one) a totally minimal Android project which does nothing, but builds fine and publishes artifacts to Nexus (as your does), I/we could try to take a look at it to solve the problem with GNPP <-> Android project interaction. Otherwise, it could be hard to do anything about that :-(.

It would be best to publish it to a separate GitHub repo with set up GH Actions (to be able to play with it there) and after (hopefully) successful triage and fix, it could be eventually also converted to an automatic regression e2e tests (as we currently have for single and multi-project regular Java builds) to prevent that kind of problems also in the future. Does it sound good for you? :-).

**Comment by jahirfiquitiva** [comment] 2021-03-03 02:28
oh, that looks like quite some work to be done ... I will create that project in the next days and let you know... thanks for the help

**Comment by szpak** [comment] 2021-03-03 20:28
Maybe removing (most of) the source code from your current project + some dummy GH action which builds the project (and where it is possible to add later on secrets and try to push it to Nexus) will be easier that configuring it from scratch with a new generated project? Just choose the line of least resistance.

**Comment by szpak** [comment] 2021-03-04 20:44
As the first several comments are not much related to the conclusion, I created #75 to cover better support for releasing Android projects. Closing this one to avoid confusion.

**Closed by szpak** 2021-03-04 20:44 UTC

**Comment by flutterq** [comment] 2021-05-13 15:18
[[Solved] AbstractDynamicObject$CustomMessageMissingMethodException error in android
]([Solved] AbstractDynamicObject$CustomMessageMissingMethodException error in android
)
